### ISSUE TITLE
connectivity graph not responsive to selection of weights

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/geoda#1520]
V 87

After creating a connectivity graph for a given spatial weights, the graph is unresponsive to a change in the weights selection. For example, in Guerry, using the MDS weights gives a graph, then switch the active weights to queen contiguity, the graph is still the MDS weights, not the contiguity graph.

**Comment by lanselin** [comment]
in V91, the connectivity graph updates for a different selection of weight, but all graphs are updated. The update should only be for the currently active map/graph, not for all of them. For example, when a weight selection is changed for a LISA calculation, this does not affect existing cluster maps, only the current analysis. The update for the connectivity graph should be similar, only affecting the current map window.

**Comment by lixun910** [comment]
@lanselin  This should be fixed in latest GeoDa1.12.1.91-Installer-CartoFIx.dmg

**Comment by lixun910** [comment]
See: change weights selection to knn=6 doesn't impact LISA which use queen weights <img width="1183" alt="screen shot 2018-02-09 at 10 14 29 am" src="https://user-images.githubusercontent.com/2423887/36040202-0faa8330-0d82-11e8-89a3-a945f251fa3f.png">

**Comment by lanselin** [comment]
This is not fixed - V 1.12.1.93

If one selects the connectivity graph, a window opens with a themeless map and the graph for the currently active weights. If one selects a different weight, the graph is updated in the map. If one selects connectivity graph again, a new themeless map opens with the graph, but all the graphs are updated to the currently active weights.

So, it is not possible to compare two graphs side by side, all the graphs are always the same and refer to the currently active weight.

I believe the proper design would be to have the graph only pertain to one active window. So, each time a different weight becomes active, a new connectivity graph window is created, but not have the synchronization that all graph windows show the same graph.

**Comment by lanselin** [comment]
There may be two issues at work here.

One is where we have a map, and a currently active weight, and the Connectivity > Show Graph is selected the graph should reflect the current weight. If the current active weights is changed, this graph should change, as it does.

However, when one selects connectivity graph from the weights manager, this should create a separate map window with the graph for the selected weight on it. This window should also list the weight to which the graph pertains (as it is there is no way of knowing this without looking at the weights manager). However, when a different weight is selected and the connectivity graph button is clicked, there should be a new map window with the graph for that weight. This action should not update the graphs that were created using Connectivity > Show Graph.

So, what I am suggesting is to separate the behavior of Connectivity > Show Graph in the map window (pertaining to the current weight) from that in the Connectivity Graph button in the weight manager, which should not update all the weights.

**Comment by lanselin** [comment]
Sorry, typo in the comment above. Just to be clear:

- Connectivity > Show Graph in map always pertains to the active weight

- Connectivity Graph in the weights manager does not update other connectivity graph windows, but creates a separate window with a graph. However, if there is a map with connectivity > show graph active, that graph will be updated.

Hope this makes sense :-)

**Comment by luluzhou766** [comment]
Window 7
Geoda 1.12.1.97
Verified 

1)	The “connectivity graph” opened in map (bottom left first map) updates with changing active weights
2)	The “connectivity graph” opened from weights manager does not update with changing active weights (bottom right two maps. steps: open connectivity graph -> themeless map -> change current map type -> box map) 
3)	The “connectivity graph” opened in cluster map does not update with changing active weights. (upper right two maps)

<img width="956" alt="01" src="https://user-images.githubusercontent.com/36253697/36689156-8c38bf28-1b26-11e8-94da-584fb6c487f9.PNG">
<img width="957" alt="02" src="https://user-images.githubusercontent.com/36253697/36689157-8c5b4a34-1b26-11e8-978b-791744238198.PNG">

**Comment by jkoschinsky** [comment]
GeoDa 1.99
Mac OSX

confirmed: 
maps with Connectivity --> Show Graph are updated when weights are changed
Connectivity Graph maps don't update in this case

maps with Connectivity --> Show Graph do not show which weights are displayed in the header (see below): List this as in the header of the Connectivity Graph maps

<img width="1203" alt="screen shot 2018-03-05 at 11 01 30 am" src="https://user-images.githubusercontent.com/13679743/36988597-dfd9a582-2064-11e8-8230-e58fbfef8031.png">

**Comment by lixun910** [comment]
the header will only be shown when user click "Connectivity Map" and "Connectivity Graph" from Weights manage dialog.  Otherwise it will break original map title (e.g. Hinge=1.5: hoval)

**Comment by lanselin** [comment]
i think this is fine, since the connectivity graph in a regular map depends on the currently active weights, so one always knows to what weights it pertains. this is in contrast with the "connectivity graph" or map invoked from the weights manager, which is separate from an actual choropleth map, and one can have several open, each created from a different weights specification.

that's the convention I outlined above.
